title: Gulam Choudhury
logo: assests/img/Headshot_circle.png
description: Personal Website of Gulam Sulaman Choudhury
#show_downloads: true
theme: jekyll-theme-minimal
social links:
- <a href="www.linkedin.com/in/abirsulaman" target="_blank">LinkedIn</a> 
